export const FETCH_STARTED = 'HOME/FETCH_STARTED';
export const FETCH_SUCCESS = 'HOME/FETCH_SUCCESS';
export const FETCH_FAILURE = 'HOME/FETCH_FAILURE';

export const FETCH_PRODUCT_STARTED = 'HOME/FETCH_PRODUCT_STARTED';
export const FETCH_PRODUCT_SUCCESS = 'HOME/FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_FAILURE = 'HOME/FETCH_PRODUCT_FAILURE';